const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<1?4:2}).format(n):'—';
const compact=n=>Number.isFinite(n)?'$'+new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n):'—';
const time=s=>s?new Date(s).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';
const chainName=c=>({solana:'Solana',ethereum:'Ethereum',bsc:'BNB Chain',arbitrum:'Arbitrum',optimism:'Optimism',base:'Base',polygon:'Polygon',ink:'Ink',hyperevm:'HyperEVM',mantle:'Mantle'}[c]||c);
const colors=['#c5ed85','#8ab7e8','#b5a0dd','#e5b878','#79bba8','#d28a8a','#9fc5b8','#b7bc82','#8f9fbf','#d1b4cb'];
const preferred=['SPY','NVDA','AAPL','MSFT','QQQ','GOOGL','AMZN','TSLA','MCD','VT','MRNA','GLD','TLT'];
let tokens=[],byId=new Map(),groups=[],basket=[],markets=new Map(),marketPending=new Map(),selectedTicker='',versionGeneration=0,chartGeneration=0,quoteGeneration=0,currentPage='builder',limit=30,walletProvider=null,walletAddress=null;
let reviewSnapshot=[],pluginLoading=null;
let plans=read('folio-plans-v2',[]),stars=read('folio-watchlist-v2',[]);
function loadSwapPlugin(){
 if(window.Jupiter?.init)return Promise.resolve();
 if(pluginLoading)return pluginLoading;
 pluginLoading=new Promise((resolve,reject)=>{
  const script=document.createElement('script');script.src='https://plugin.jup.ag/plugin-v1.js';script.async=true;
  const timer=setTimeout(()=>{script.remove();pluginLoading=null;reject(new Error('Swap interface timed out. Use the Jupiter link or retry.'))},25000);
  script.onload=()=>{clearTimeout(timer);if(window.Jupiter?.init)resolve();else{pluginLoading=null;reject(new Error('Swap interface unavailable. Use the Jupiter link.'))}};
  script.onerror=()=>{clearTimeout(timer);script.remove();pluginLoading=null;reject(new Error('Could not load Jupiter. Use the external trading link.'))};
  document.head.append(script);
 });return pluginLoading;
}
async function openSwap(index){
 const slice=reviewSnapshot[index];if(!slice||slice.t.chain!=='solana'||slice.t.halted)return;
 $('#review-dialog').close();toast('Loading Jupiter. Review the swap before approving in your wallet.');
 try{await loadSwapPlugin();window.Jupiter.init({displayMode:'modal',autoConnect:false,defaultExplorer:'Solscan',branding:{name:'Folio'},formProps:{swapMode:'ExactIn',initialAmount:String(Math.round(slice.amount*1e6)),initialInputMint:'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',initialOutputMint:slice.t.address,fixedMint:slice.t.address,fixedAmount:true},onSuccess:()=>toast('Jupiter reported this swap complete. Verify the transaction in your wallet. Other slices remain separate.'),onSwapError:()=>toast('Swap was not completed. Check Jupiter and your wallet before trying again.')});}
 catch(e){toast(e.message);$('#review-dialog').showModal()}
}
plans=Array.isArray(plans)?plans.filter(p=>p&&typeof p.name==='string'&&typeof p.id==='string'&&Array.isArray(p.slices)&&p.slices.every(s=>typeof s.id==='string'&&Number.isFinite(s.weight))&&Number.isFinite(p.amount)):[];
stars=Array.isArray(stars)?stars.filter(s=>typeof s==='string'):[];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('Browser storage is unavailable. Changes will last for this session only.');return false}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}
async function api(route,params={}){const r=await fetch('/api/'+route+'?'+new URLSearchParams(params));const d=await r.json();if(!r.ok)throw new Error(d.error||'Provider unavailable');return d}
function token(id){return byId.get(id)}
function assetLogo(t){let logo='';try{const u=new URL(t.logo);if(u.protocol==='https:')logo=u.href}catch{}return `<span class="ticker-tile">${esc(t.ticker.slice(0,5))}${logo?`<img src="${esc(logo)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:''}</span>`}
document.addEventListener('error',e=>{if(e.target.matches?.('.ticker-tile img'))e.target.remove()},true);
function identity(t){return `<div class="identity">${assetLogo(t)}<div><strong>${esc(t.name)}</strong><small>${esc(t.symbol)} · ${esc(t.issuer)} · ${esc(chainName(t.chain))}</small></div></div>`}
function schedule(){const f=$('#frequency').value,n=Number($('#schedule-value').value);return {frequency:f,interval:n,label:({once:'One time',daily:'Every day',weekly:'Every week',interval:`Every ${n} days`,monthly:`Monthly on day ${n}`})[f]}}
function amount(){return Number($('#amount').value)}
function validation(){const base=FolioMath.validate(amount(),basket);if(base)return base;if(basket.some(s=>!token(s.id)))return 'Some saved assets are missing from the current issuer catalog.';const s=schedule();if(['interval','monthly'].includes(s.frequency)&&(!Number.isInteger(s.interval)||s.interval<1||s.interval>(s.frequency==='monthly'?28:365)))return s.frequency==='monthly'?'Choose a calendar day from 1 to 28.':'Choose an interval from 1 to 365 days.';return ''}
function sliceAmounts(){if(!basket.length)return [];if(Math.abs(basket.reduce((s,x)=>s+x.weight,0)-100)<.001&&Number.isFinite(amount()))return FolioMath.splitCents(amount(),basket.map(s=>s.weight));return basket.map(s=>(Number.isFinite(amount())?amount():0)*s.weight/100)}
function stats(t){const m=markets.get(t.id);if(!m)return '<div><small>MARKET DATA</small><strong>Loading…</strong></div>';if(m.error)return `<div><small>MARKET DATA</small><strong title="${esc(m.error)}">Unavailable · retry refresh</strong></div>`;if(!m.price)return '<div><small>MARKET DATA</small><strong>No indexed pool</strong></div>';return `<div><small>POOL PRICE</small><strong>${money(m.price)}</strong></div><div><small>24H CHANGE</small><strong class="${m.change24h>=0?'positive':'negative'}">${m.change24h===null?'—':(m.change24h>=0?'+':'')+m.change24h.toFixed(2)+'%'}</strong></div><div><small>POOL LIQUIDITY</small><strong>${compact(m.liquidity)}</strong></div><div><small>CHECKED</small><strong>${time(m.asOf)}</strong></div>`}
async function getMarket(id){if(markets.has(id)&&Date.now()-new Date(markets.get(id).asOf||0).getTime()<60000)return markets.get(id);if(marketPending.has(id))return marketPending.get(id);const p=api('market',{id}).then(d=>{markets.set(id,d);return d}).catch(e=>{const d={error:e.message};markets.set(id,d);return d}).finally(()=>marketPending.delete(id));marketPending.set(id,p);return p}
function renderRows(){const amounts=sliceAmounts();$('#asset-rows').innerHTML=basket.length?basket.map((s,i)=>{const t=token(s.id);if(!t)return `<div class="asset-row">Asset no longer in catalog <button data-remove="${esc(s.id)}">Remove</button></div>`;return `<div class="asset-row" data-row="${esc(s.id)}"><div class="asset-main">${identity(t)}<label class="weight"><button data-step="-1" data-id="${esc(s.id)}" aria-label="Decrease ${esc(t.ticker)} allocation">−</button><input aria-label="${esc(t.ticker)} allocation" data-weight="${esc(s.id)}" type="number" min="0" max="100" step="0.01" value="${s.weight}"><span>%</span><button data-step="1" data-id="${esc(s.id)}" aria-label="Increase ${esc(t.ticker)} allocation">+</button></label><span class="slice-amount">${money(amounts[i])}</span></div><div class="market-stats">${stats(t)}</div><div class="row-tools"><button data-versions="${esc(t.ticker)}">Compare token versions ↗</button><button data-remove="${esc(s.id)}" aria-label="Remove ${esc(t.ticker)}">Remove ×</button></div></div>`}).join(''):'<div class="empty">A fresh canvas.<br>Add a stock or ETF to start building your portfolio.</div>';update();updateHistorySelect();basket.forEach(s=>getMarket(s.id).then(()=>{const row=$$('[data-row]').find(r=>r.dataset.row===s.id);if(row&&token(s.id))row.querySelector('.market-stats').innerHTML=stats(token(s.id));if($('#history-asset').value===s.id)$('#chart-price').textContent=money(markets.get(s.id)?.price)}))}
function update(){const sum=basket.reduce((s,x)=>s+x.weight,0);$('#allocation-status').textContent=`${Number(sum.toFixed(2))}% of funds allocated`;$('#allocation-status').className=Math.abs(sum-100)<.001?'positive':'negative';$('#slice-count').textContent=basket.length+' assets';$('#asset-count').textContent=basket.length;$('#allocation-bar').innerHTML=basket.map((s,i)=>`<i style="width:${Math.max(0,s.weight)}%;background:${colors[i]}"></i>`).join('');let cursor=0;$('#donut').style.background=sum>0?`conic-gradient(${basket.map((s,i)=>{const start=cursor;cursor+=Math.max(0,s.weight)/sum*100;return `${colors[i]} ${start}% ${cursor}%`}).join(',')})`:'#303d26';$('#legend').innerHTML=basket.map((s,i)=>`<div class="legend-row"><i style="background:${colors[i]}"></i><span>${esc(token(s.id)?.ticker||'?')}</span><span>${s.weight}%</span></div>`).join('');const networkCount=new Set(basket.map(s=>token(s.id)?.chain)).size;$('#mix-networks').textContent=networkCount+' network'+(networkCount===1?'':'s');$('#total').textContent=money(amount());$('#validation').textContent=validation();$('#review').disabled=!!validation();$('#save-plan').disabled=!!validation();const amounts=sliceAmounts();$$('.slice-amount').forEach((e,i)=>e.textContent=money(amounts[i]));$$('[data-amount]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.amount)===amount()));const sch=schedule();$('#schedule-extra').hidden=!['interval','monthly'].includes(sch.frequency);$('#schedule-extra-label').textContent=sch.frequency==='monthly'?'Day of month (1–28)':'Interval in days';$('#schedule-value').max=sch.frequency==='monthly'?28:365;$('#schedule-description').textContent=sch.frequency==='once'?'A one-time investment plan.':`${sch.label} · ${money(amount())} per round. Saved preference, not an active order.`;}
function equalize(){if(!basket.length)return;const base=Math.floor(10000/basket.length)/100;basket.forEach((s,i)=>s.weight=i===basket.length-1?Number((100-base*(basket.length-1)).toFixed(2)):base);renderRows()}
function choose(id){const t=token(id);if(!t)return;const existing=basket.find(s=>token(s.id)?.ticker===t.ticker);if(existing){existing.id=id;toast('Token version updated.')}else{if(basket.length>=10)return toast('Use up to 10 assets in one plan.');basket.push({id,weight:0});equalize();toast('Asset added. Allocations split equally.')}$('#version-dialog').close();$('#asset-dialog').close();renderRows();page('builder')}
function groupIdentity(g){return `<div class="identity">${assetLogo({...g.tokens.find(t=>t.logo),ticker:g.ticker})}<div><strong>${esc(g.name)}</strong><small>${esc(g.ticker)} · ${g.tokens.length} token versions · ${[...new Set(g.tokens.map(t=>t.issuer))].join(' / ')}</small></div></div>`}
function filteredGroups(query='',chain='',issuer=''){const q=query.trim().toLowerCase();return groups.map(g=>({...g,tokens:g.tokens.filter(t=>(!chain||t.chain===chain)&&(!issuer||t.issuer===issuer))})).filter(g=>g.tokens.length&&(!q||`${g.ticker} ${g.name}`.toLowerCase().includes(q)||g.tokens.some(t=>t.address.toLowerCase()===q)))}
function renderCatalog(){const list=filteredGroups($('#search').value).slice(0,35);$('#catalog').innerHTML=list.length?list.map(g=>`<div class="catalog-row">${groupIdentity(g)}<button class="compare" data-versions="${esc(g.ticker)}">Compare ↗</button></div>`).join(''):'<div class="empty">No matches in the current issuer catalogs.</div>'}
function discoveryRow(g){return `<div class="discovery-row">${groupIdentity(g)}<span>${[...new Set(g.tokens.map(t=>chainName(t.chain)))].slice(0,3).map(esc).join(' · ')}${new Set(g.tokens.map(t=>t.chain)).size>3?' + more':''}</span><button class="compare" data-versions="${esc(g.ticker)}">Compare ↗</button><button class="star ${stars.includes(g.ticker)?'on':''}" data-star="${esc(g.ticker)}" aria-label="${stars.includes(g.ticker)?'Unwatch':'Watch'} ${esc(g.ticker)}">${stars.includes(g.ticker)?'★':'☆'}</button></div>`}
function renderDiscover(){const list=filteredGroups($('#discover-search').value,$('#chain-filter').value,$('#issuer-filter').value);$('#result-count').textContent=`${list.length.toLocaleString()} underlying tickers`;$('#discover-results').innerHTML=list.length?list.slice(0,limit).map(discoveryRow).join(''):'<div class="empty">No matching assets. Try another search or network.</div>';$('#show-more').hidden=list.length<=limit}
function renderWatchlist(){$('#watch-count').textContent=stars.length;const list=groups.filter(g=>stars.includes(g.ticker));$('#watchlist-content').innerHTML=list.length?`<div class="panel">${list.map(discoveryRow).join('')}</div>`:'<div class="panel empty">Keep your next idea close.<br>Star an asset in Discover to add it to your watchlist.</div>'}
function sortedVersions(g){return [...g.tokens].sort((a,b)=>((a.chain==='solana'?0:a.chain==='ethereum'?2:1)-(b.chain==='solana'?0:b.chain==='ethereum'?2:1))||a.issuer.localeCompare(b.issuer))}
async function versions(ticker){const g=groups.find(g=>g.ticker===ticker);if(!g)return;selectedTicker=ticker;const gen=++versionGeneration;$('#version-title').textContent=`${ticker} · ${g.tokens.length} token versions`;$('#version-dialog').showModal();const list=sortedVersions(g);$('#version-list').innerHTML=list.map(t=>`<article class="version-row" data-version="${esc(t.id)}"><div><h3>${esc(t.symbol)} <span class="subtle">/ ${esc(chainName(t.chain))}</span></h3><p>${esc(t.issuer)} · ${t.halted?'Issuer reports trading halted':'Address matched to issuer catalog'}</p><p>${esc(t.dividend)}</p><a class="address" href="${explorer(t)}" target="_blank" rel="noopener noreferrer">${esc(t.address)} ↗</a></div><div class="version-price">${versionPrice(markets.get(t.id))}</div><div class="version-actions"><button data-choose="${esc(t.id)}">${basket.some(s=>s.id===t.id)?'Selected ✓':'Use this token'}</button><button data-copy="${esc(t.address)}">Copy address</button><a href="${esc(t.source)}" target="_blank" rel="noopener noreferrer">Issuer source ↗</a></div></article>`).join('');for(let i=0;i<list.length;i+=4){if(gen!==versionGeneration||!$('#version-dialog').open)break;await Promise.all(list.slice(i,i+4).map(async t=>{const m=await getMarket(t.id);if(gen!==versionGeneration)return;const row=$$('[data-version]').find(el=>el.dataset.version===t.id);if(row)row.querySelector('.version-price').innerHTML=versionPrice(m)}))}}
function versionPrice(m){return !m?'<span>Loading pool data…</span>':m.error?'<span>Data unavailable</span>':m.price?`<strong>${money(m.price)}</strong><span>Liquidity ${compact(m.liquidity)}</span><span>24h volume ${compact(m.volume24h)}</span><span>Retrieved ${time(m.asOf)}</span>`:'<span>No indexed pool</span><span>Other routes may exist</span>'}
function explorer(t){const base={solana:'https://solscan.io/token/',ethereum:'https://etherscan.io/token/',bsc:'https://bscscan.com/token/',arbitrum:'https://arbiscan.io/token/',base:'https://basescan.org/token/',optimism:'https://optimistic.etherscan.io/token/',polygon:'https://polygonscan.com/token/'}[t.chain];return base?base+encodeURIComponent(t.address):t.source}
function tradeLink(t){if(t.chain==='solana')return 'https://jup.ag/swap/USDC-'+encodeURIComponent(t.address);const m=markets.get(t.id);return m?.url||explorer(t)}
function updateHistorySelect(){const old=$('#history-asset').value;$('#history-asset').innerHTML=basket.map(s=>{const t=token(s.id);return t?`<option value="${esc(s.id)}">${esc(t.symbol)} · ${esc(chainName(t.chain))}</option>`:''}).join('');if(basket.some(s=>s.id===old))$('#history-asset').value=old;const selected=$('#history-asset').value;if(selected!==updateHistorySelect.last){updateHistorySelect.last=selected;drawHistory()}}
async function drawHistory(){const gen=++chartGeneration,id=$('#history-asset').value;$('#chart-change').textContent='';$('#chart-price').textContent=money(markets.get(id)?.price);if(!id){$('#chart').innerHTML='<div class="empty">Add an asset to explore real token price history.</div>';return}$('#chart').innerHTML='<div class="empty">Loading historical pool closes…</div>';try{const d=await api('history',{id});if(gen!==chartGeneration)return;if(d.points.length<2){$('#chart').innerHTML=`<div class="empty">${esc(d.reason||'Not enough historical data for this pool.')}<br>No synthetic history is substituted.</div>`;return}const ps=d.points,low=Math.min(...ps.map(p=>p.value)),high=Math.max(...ps.map(p=>p.value)),range=high-low||1;const W=900,H=170;const points=ps.map((p,i)=>[i/(ps.length-1)*W,12+(1-(p.value-low)/range)*(H-24)]);const path=points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');const pct=(ps.at(-1).value/ps[0].value-1)*100;$('#chart-change').innerHTML=`<span class="${pct>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2)}%</span><div class="micro">Across ${ps.length} daily observations</div>`;$('#chart').innerHTML=`<svg viewBox="0 0 900 200" preserveAspectRatio="none" role="img" aria-label="${esc(token(id).symbol)} daily token pool price chart"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#a6ce72" stop-opacity=".16"/><stop offset="100%" stop-color="#a6ce72" stop-opacity="0"/></linearGradient></defs>${[30,75,120,165].map(y=>`<line x1="0" y1="${y}" x2="900" y2="${y}" stroke="#e0e7d8" stroke-dasharray="3 5"/>`).join('')}<path d="${path} L900,175 L0,175 Z" fill="url(#chart-fill)"/><path d="${path}" stroke="#8eb755" stroke-width="2.2" fill="none" vector-effect="non-scaling-stroke"/>${points.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="transparent"><title>${new Date(ps[i].time).toLocaleDateString()}: ${money(ps[i].value)}</title></circle>`).join('')}<text x="0" y="197" fill="#8b9d7c" font-size="15">${new Date(ps[0].time).toLocaleDateString()}</text><text x="900" y="197" text-anchor="end" fill="#8b9d7c" font-size="15">${new Date(ps.at(-1).time).toLocaleDateString()}</text></svg>`;$('#chart-caption').textContent=`${token(id).symbol} · ${d.label}. Not underlying-stock returns or a basket backtest.`}catch(e){if(gen!==chartGeneration)return;$('#chart').innerHTML=`<div class="empty">Historical data is temporarily unavailable.<br>${esc(e.message)}<button class="text-button" id="retry-chart">Try again ↻</button></div>`}}
function savePlan(){if(validation())return;const p={id:crypto.randomUUID(),name:$('#basket-name').value.trim()||'Untitled plan',amount:amount(),schedule:schedule(),slices:basket.map(s=>({...s})),createdAt:new Date().toISOString()};plans.push(p);write('folio-plans-v2',plans);renderPlans();toast('Investment plan saved. No funds moved or orders scheduled.')}
function renderPlans(){$('#plan-count').textContent=plans.length;$('#plans-content').innerHTML=plans.length?`<div class="plan-grid">${plans.map(p=>`<article class="panel saved-plan"><span class="overline">SAVED PLAN · NOT AN ACTIVE ORDER</span><h3>${esc(p.name)}</h3><p>Created ${new Date(p.createdAt).toLocaleDateString()}</p><div class="plan-amount">${money(p.amount)} <span class="subtle">/ round</span></div><p>${esc(p.schedule?.label||'One time')}</p><div class="plan-tokens">${p.slices.map(s=>`<span>${esc(token(s.id)?.ticker||'Unavailable token')} ${s.weight}%</span>`).join('')}</div><p>Funding is not reserved. Review current quotes and eligibility before each purchase.</p><div class="plan-actions"><button class="secondary" data-load="${esc(p.id)}">Load plan ↗</button><button class="text-button" data-export="${esc(p.id)}">Export</button><button class="text-button" data-delete="${esc(p.id)}">Delete</button></div></article>`).join('')}</div>`:'<div class="panel empty">Make room for your next idea.<br>Save a basket from the plan builder to keep it here.</div>'}
async function review(){if(validation())return;$('#review-dialog').showModal();const gen=++quoteGeneration;const amounts=sliceAmounts();const snapshot=basket.map((s,i)=>({t:token(s.id),amount:amounts[i]}));reviewSnapshot=snapshot;$('#review-note').textContent=`${money(amount())} planned · ${schedule().label}. Recurring schedules are not executed. Quotes are indicative and must be refreshed at the venue.`;$('#review-lines').innerHTML=snapshot.map((x,i)=>`<article class="review-row"><div class="review-row-top">${identity(x.t)}<strong>${money(x.amount)} USDC</strong></div><div id="quote-${i}"><p>${x.t.chain==='solana'?'Requesting a live indicative quote…':'This network uses external venue execution.'}</p></div>${x.t.chain==='solana'&&!x.t.halted?`<button class="secondary" data-trade="${i}">Open swap in Folio ↗</button>`:''}<a href="${tradeLink(x.t)}" target="_blank" rel="noopener noreferrer">${x.t.chain==='solana'?'Review & trade on Jupiter':markets.get(x.t.id)?.url?'View market on DEX Screener':'Inspect verified contract'} ↗</a></article>`).join('');for(let i=0;i<snapshot.length;i++){if(gen!==quoteGeneration||!$('#review-dialog').open)break;const x=snapshot[i];if(x.t.chain!=='solana')continue;try{const q=await api('quote',{id:x.t.id,amount:x.amount});if(gen!==quoteGeneration)return;$('#quote-'+i).innerHTML=q.status==='quoted'?`<div class="quote-stats"><span>Route: ${esc(q.router||'Jupiter')}</span><span>Provider fee: ${q.feeBps===null?'Not reported':(q.feeBps/100).toFixed(2)+'%'}</span>${q.outputDecimals!==null?`<span>≈ ${(Number(q.outAmount)/10**q.outputDecimals).toFixed(6)} raw token units</span>`:''}</div><p>Retrieved ${time(q.asOf)} · indicative, not locked. Network costs are confirmed at the venue. Token display multipliers may affect wallet balances.</p>`:`<p class="negative">No quote: ${esc(q.message)}. You can still check availability at the venue.</p>`}catch(e){if(gen===quoteGeneration)$('#quote-'+i).innerHTML=`<p class="negative">Quote unavailable: ${esc(e.message)}</p>`}}}
function page(name){currentPage=name;['builder','discover','plans','watchlist'].forEach(n=>$('#'+n+'-page').hidden=n!==name);$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const titles={builder:['Plan builder','Your portfolio. <em>Your perspective.</em>','Bring your ideas together in a basket of tokenized stocks and ETFs.'],discover:['Discover assets','A world of assets. <em>One clear view.</em>','Find the underlying stock. Compare verified token versions across issuers and networks.'],plans:['Saved plans','Good ideas deserve <em>a plan.</em>','Your saved allocations and schedules. Nothing trades automatically.'],watchlist:['Watchlist','Keep your next idea <em>in sight.</em>','A personal shortlist of the assets you want to explore.']};$('#page-label').textContent=titles[name][0];$('#page-title').innerHTML=titles[name][1];$('#page-subtitle').textContent=titles[name][2];if(name==='discover')renderDiscover();if(name==='plans')renderPlans();if(name==='watchlist')renderWatchlist()}
async function loadData(){const btn=$('#refresh');btn.disabled=true;$('#connection-status').innerHTML='<i></i> Connecting data';try{const d=await api('catalog');tokens=d.tokens;byId=new Map(tokens.map(t=>[t.id,t]));const grouped=new Map();tokens.forEach(t=>{if(!grouped.has(t.ticker))grouped.set(t.ticker,{ticker:t.ticker,name:t.name,tokens:[]});grouped.get(t.ticker).tokens.push(t)});groups=[...grouped.values()].sort((a,b)=>{const ai=preferred.indexOf(a.ticker),bi=preferred.indexOf(b.ticker);return (ai<0?999:ai)-(bi<0?999:bi)||a.ticker.localeCompare(b.ticker)});$('#chain-filter').innerHTML='<option value="">All networks</option>'+[...new Set(tokens.map(t=>t.chain))].sort().map(c=>`<option value="${c}">${chainName(c)}</option>`).join('');$('#connection-status').innerHTML='<i></i> Live data connected';$('#data-notice').classList.remove('error');$('#data-notice').textContent=`${groups.length.toLocaleString()} underlying tickers · ${tokens.length.toLocaleString()} verified deployments · ${d.sources.filter(s=>s.status==='available').length} issuer feeds · Catalog retrieved ${time(d.asOf)}. ${d.sources.some(s=>s.status!=='available')?'Partial coverage: an issuer feed is unavailable. ':''}Market observations are not executable prices.`;$('#source-status').innerHTML=d.sources.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} catalog ↗</a> · ${esc(s.status)}</p>`).join('');if(!basket.length&&!loadData.initialized){const saved=read('folio-draft-v2',null);if(saved&&Array.isArray(saved.slices)&&saved.slices.length<=10&&saved.slices.every(s=>token(s.id)&&Number.isFinite(s.weight))){basket=saved.slices;$('#basket-name').value=typeof saved.name==='string'?saved.name:'My portfolio';if(Number.isFinite(saved.amount))$('#amount').value=saved.amount}else starter('core');loadData.initialized=true;}markets.clear();renderRows();renderPlans();renderWatchlist();renderDiscover();}catch(e){$('#connection-status').textContent='Data unavailable';$('#data-notice').classList.add('error');$('#data-notice').textContent=e.message+' Use Refresh data to retry. No fabricated prices are shown.';if(!tokens.length)$('#asset-rows').innerHTML='<div class="empty">Issuer catalogs could not be loaded.<br>Check the connection and refresh.</div>';update();}finally{btn.disabled=false}}
function starter(type){basket=[];const list=type==='tech'?['NVDA','AAPL','MSFT']:type==='core'?['SPY','QQQ','NVDA']:[];list.forEach((ticker,i)=>{const t=tokens.find(t=>t.ticker===ticker&&t.chain==='solana'&&t.issuer==='xStocks')||tokens.find(t=>t.ticker===ticker);if(t)basket.push({id:t.id,weight:type==='tech'?[40,35,25][i]:[60,25,15][i]})});if(basket.length!==list.length&&basket.length)equalize();else renderRows()}
function persistDraft(){write('folio-draft-v2',{name:$('#basket-name').value,amount:amount(),slices:basket})}
async function connectWallet(){if(walletAddress){try{await walletProvider.disconnect()}catch{}walletAddress=null;$('#wallet span').textContent='Connect wallet';return}const p=window.phantom?.solana||window.solflare||window.solana;if(!p?.connect){toast('Open Folio in a browser with Phantom or Solflare installed. No demo wallet is substituted.');return}try{const result=await p.connect();walletProvider=p;walletAddress=(result?.publicKey||p.publicKey)?.toString();if(!walletAddress)throw new Error('No public address returned');$('#wallet span').textContent=walletAddress.slice(0,4)+'…'+walletAddress.slice(-4);toast('Wallet connected. No transaction signing or trading permissions requested.');p.on?.('disconnect',()=>{walletAddress=null;$('#wallet span').textContent='Connect wallet'});p.on?.('accountChanged',key=>{walletAddress=key?.toString()||null;$('#wallet span').textContent=walletAddress?walletAddress.slice(0,4)+'…'+walletAddress.slice(-4):'Connect wallet'})}catch{toast('Wallet connection was not completed.')}}
$('#wallet').onclick=connectWallet;$('#refresh').onclick=()=>{loadData().then(drawHistory)};$('#equalize').onclick=()=>{equalize();persistDraft()};$('#review').onclick=review;$('#refresh-quotes').onclick=review;$('#save-plan').onclick=savePlan;$('#sources-button').onclick=()=>$('#info-dialog').showModal();$('#history-asset').onchange=drawHistory;$('#add-asset').onclick=()=>{$('#search').value='';renderCatalog();$('#asset-dialog').showModal()};$('#search').oninput=renderCatalog;$('#amount').oninput=()=>{update();persistDraft()};$('#basket-name').oninput=persistDraft;$('#schedule-value').oninput=update;$('#frequency').onchange=()=>{if($('#frequency').value==='monthly')$('#schedule-value').value=1;else if($('#frequency').value==='interval')$('#schedule-value').value=30;update()};['discover-search','chain-filter','issuer-filter'].forEach(id=>$('#'+id).addEventListener(id==='discover-search'?'input':'change',()=>{limit=30;renderDiscover()}));$('#show-more').onclick=()=>{limit+=30;renderDiscover()};$('#asset-rows').oninput=e=>{if(e.target.dataset.weight){const s=basket.find(s=>s.id===e.target.dataset.weight);s.weight=Number(e.target.value);update();persistDraft()}};
$('#review-dialog').addEventListener('close',()=>quoteGeneration++);$('#version-dialog').addEventListener('close',()=>versionGeneration++);
$('.brand').onclick=e=>{e.preventDefault();page('builder')};
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.trade!==undefined)openSwap(Number(d.trade));if(d.page)page(d.page);if(b.classList.contains('close'))b.closest('dialog').close();if(d.amount){$('#amount').value=d.amount;update();persistDraft()}if(d.template){starter(d.template);persistDraft()}if(d.remove){basket=basket.filter(s=>s.id!==d.remove);renderRows();persistDraft()}if(d.step){const s=basket.find(s=>s.id===d.id);s.weight=Math.max(0,Math.min(100,Number((s.weight+Number(d.step)).toFixed(2))));renderRows();persistDraft()}if(d.versions)versions(d.versions);if(d.choose){choose(d.choose);persistDraft()}if(d.copy){try{await navigator.clipboard.writeText(d.copy);toast('Verified contract address copied.')}catch{toast('Clipboard unavailable. Select and copy the displayed address.')}}if(d.star){stars=stars.includes(d.star)?stars.filter(t=>t!==d.star):[...stars,d.star];write('folio-watchlist-v2',stars);renderWatchlist();renderDiscover()}if(d.load){const p=plans.find(p=>p.id===d.load);basket=p.slices.map(s=>({...s}));$('#basket-name').value=p.name;$('#amount').value=p.amount;$('#frequency').value=p.schedule?.frequency||'once';$('#schedule-value').value=p.schedule?.interval||1;renderRows();page('builder');persistDraft();toast('Plan loaded. Check current markets before purchasing.')}if(d.delete){plans=plans.filter(p=>p.id!==d.delete);write('folio-plans-v2',plans);renderPlans();toast('Saved plan deleted.')}if(d.export){const p=plans.find(p=>p.id===d.export);const url=URL.createObjectURL(new Blob([JSON.stringify({...p,assets:p.slices.map(s=>({...s,token:token(s.id)}))},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='folio-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}if(b.id==='retry-chart')drawHistory()});
update();renderPlans();renderWatchlist();loadData();
